//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangCB
    {
        public string Sohoso { get; set; }
        public string Hoten { get; set; }
        public string Tendangdung { get; set; }
        public System.DateTime Ngaysinh { get; set; }
        public string Noisinh { get; set; }
        public string Quequan { get; set; }
        public string Noiohiennay { get; set; }
        public string Dantoc { get; set; }
        public string Tongiao { get; set; }
        public string Nghenghiepgiadinh { get; set; }
        public string Banthan { get; set; }
        public Nullable<System.DateTime> Ngayvaodoan { get; set; }
        public string Doanthe { get; set; }
        public Nullable<System.DateTime> Ngayvaodang { get; set; }
        public Nullable<System.DateTime> TNCTdang { get; set; }
        public string Sothedang { get; set; }
        public Nullable<System.DateTime> NgayTDCA { get; set; }
        public Nullable<System.DateTime> NgayCTCA { get; set; }
        public string DVtuyen { get; set; }
        public string Nguontuyen { get; set; }
        public Nullable<System.DateTime> TNDVCQ { get; set; }
        public Nullable<System.DateTime> TNDVTT { get; set; }
        public string KyhieuDV { get; set; }
        public Nullable<System.DateTime> TNDVCS { get; set; }
        public string Capbac { get; set; }
        public Nullable<System.DateTime> Ngaycacbac { get; set; }
        public Nullable<decimal> Hesoluong { get; set; }
        public Nullable<System.DateTime> Ngayhesoluong { get; set; }
        public string Quyetdinhluong { get; set; }
        public string Lucluong { get; set; }
        public string CongtacCT { get; set; }
        public Nullable<System.DateTime> NgayCT { get; set; }
        public string QuyetdinhDD { get; set; }
        public string Congtackhac { get; set; }
        public string Congtaclamnn { get; set; }
        public string Trinhdohocvan { get; set; }
        public string TrinhdoCT { get; set; }
        public Nullable<System.DateTime> NgayTrinhdoCT { get; set; }
        public string Nanglucsotruong { get; set; }
        public string Danhhieu { get; set; }
        public string Giadinhchinhsach { get; set; }
        public string Diachihoso { get; set; }
        public string Sodienthoai { get; set; }
        public string Sobaohiem { get; set; }
        public string Anhhoso { get; set; }
    }
}
