//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bangkhenthuong
    {
        public int IDKhenthuong { get; set; }
        public Nullable<System.DateTime> Thangnam { get; set; }
        public string Hinhthuc { get; set; }
        public string Capkhenthuong { get; set; }
        public string IDCanbo { get; set; }
    }
}
