//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bangchucdanh
    {
        public int IDchucdanh { get; set; }
        public string Chucdanh { get; set; }
        public decimal Phucap { get; set; }
        public System.DateTime TNnhan { get; set; }
        public string Hinhthucbonhiem { get; set; }
        public string Soquyetdinh { get; set; }
        public Nullable<System.DateTime> TNthoi { get; set; }
        public string IDCanbo { get; set; }
    }
}
