//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bangquatrinhluong
    {
        public int IDluong { get; set; }
        public string Capbac { get; set; }
        public Nullable<System.DateTime> Thangnamcapbac { get; set; }
        public Nullable<decimal> Hesoluong { get; set; }
        public Nullable<System.DateTime> Thangnamhesoluong { get; set; }
        public string Soquyetdinh { get; set; }
        public string IDCanbo { get; set; }
    }
}
