//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bangquyhoachchucdanh
    {
        public int IDquyhoach { get; set; }
        public string Chucdanh { get; set; }
        public Nullable<System.DateTime> TNquyhoach { get; set; }
        public string Sophieu { get; set; }
        public Nullable<System.DateTime> TNthoiquyhoach { get; set; }
        public string Lydo { get; set; }
        public string IDCanbo { get; set; }
    }
}
