//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangCapuydang
    {
        public int IDcapuydang { get; set; }
        public string Capuydang { get; set; }
        public Nullable<System.DateTime> TNnhan { get; set; }
        public Nullable<System.DateTime> TNthoi { get; set; }
        public string IDCanbo { get; set; }
    }
}
