//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangQuatrinhcongtac
    {
        public int IDCongtac { get; set; }
        public Nullable<System.DateTime> Tungay { get; set; }
        public Nullable<System.DateTime> Denngay { get; set; }
        public string Chucdanh { get; set; }
        public string Congtacchuyen { get; set; }
        public string Donvicongtac { get; set; }
        public string Soquyetdinh { get; set; }
        public string IDCanbo { get; set; }
    }
}
