//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangRanuocngoai
    {
        public int IDNuocngoai { get; set; }
        public Nullable<System.DateTime> Tungay { get; set; }
        public Nullable<System.DateTime> Denngay { get; set; }
        public string Nuocden { get; set; }
        public string Lydoden { get; set; }
        public string IDCanbo { get; set; }
    }
}
