//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bangquandoi
    {
        public int IDquandoi { get; set; }
        public Nullable<System.DateTime> Nhapngu { get; set; }
        public string Capbac { get; set; }
        public string Chucvu { get; set; }
        public string Chientruong { get; set; }
        public Nullable<System.DateTime> Tnraquan { get; set; }
        public string IDCanbo { get; set; }
    }
}
