//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banglichsu
    {
        public int IDlichsu { get; set; }
        public string dacdiemlichsu { get; set; }
        public string IDCanbo { get; set; }
    }
}
