//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bangquanhe
    {
        public int IDQuanhe { get; set; }
        public string Quanhe { get; set; }
        public string Hoten { get; set; }
        public Nullable<System.DateTime> Namsinh { get; set; }
        public string Nghenghiep { get; set; }
        public string Chucdanh { get; set; }
        public string Donvicongtac { get; set; }
        public string Noio { get; set; }
        public string IDCanbo { get; set; }
    }
}
