//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bangkyluat
    {
        public int IDKyluat { get; set; }
        public string Kyluatdang { get; set; }
        public Nullable<System.DateTime> Thangnamkyluatdang { get; set; }
        public string Kyluatcoquan { get; set; }
        public Nullable<System.DateTime> Thangnamkyluatcoquan { get; set; }
        public string Tinhchatsaipham { get; set; }
        public string Tomtatsaipham { get; set; }
        public Nullable<System.DateTime> Thangnamtienbo { get; set; }
        public string IDCanbo { get; set; }
    }
}
