//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TTCBEntities : DbContext
    {
        public TTCBEntities()
            : base("name=TTCBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BangCapuydang> BangCapuydangs { get; set; }
        public virtual DbSet<BangCB> BangCBs { get; set; }
        public virtual DbSet<Bangchucdanh> Bangchucdanhs { get; set; }
        public virtual DbSet<Bangketquacongtac> Bangketquacongtacs { get; set; }
        public virtual DbSet<Bangkhenthuong> Bangkhenthuongs { get; set; }
        public virtual DbSet<Bangkyluat> Bangkyluats { get; set; }
        public virtual DbSet<Banglichsu> Banglichsus { get; set; }
        public virtual DbSet<BangQHNNN> BangQHNNNs { get; set; }
        public virtual DbSet<Bangquandoi> Bangquandois { get; set; }
        public virtual DbSet<Bangquanhe> Bangquanhes { get; set; }
        public virtual DbSet<BangQuatrinhcongtac> BangQuatrinhcongtacs { get; set; }
        public virtual DbSet<BangQuatrinhdaotao> BangQuatrinhdaotaos { get; set; }
        public virtual DbSet<Bangquatrinhluong> Bangquatrinhluongs { get; set; }
        public virtual DbSet<Bangquyhoachchucdanh> Bangquyhoachchucdanhs { get; set; }
        public virtual DbSet<Bangrangoaibienche> Bangrangoaibienches { get; set; }
        public virtual DbSet<BangRanuocngoai> BangRanuocngoais { get; set; }
        public virtual DbSet<Bangsuckhoe> Bangsuckhoes { get; set; }
    }
}
